### ISSUE TITLE
Wrong bg image for 01d case

### ISSUE THREAD

**Issue by Luper06** [sharn25/weather_ico_frog#3]
Hi, I looked at the json that fetches the images and noticed line 3:
"_01d": "https://github.com/sharn25/weather_ico_frog/raw/main/bg/10n_bg.png",

Shouldn’t it say this instead?
"_01d": "https://github.com/sharn25/weather_ico_frog/raw/main/bg/01d_bg.png",

I am using this for a scriptable widget on iPhone and am noticing the ‘clear’ weather shows the picture for the ‘rain night’. 

Thanks!

**Comment by sharn25** [comment]
Hi,Thanks, I will fix this.Regards,Sharanjit SinghSent from my iPhoneOn 17-Nov-2023, at 4:16 PM, Luper06 ***@***.***> wrote:﻿
Hi, I looked at the json that fetches the images and noticed line 3:
"_01d": "https://github.com/sharn25/weather_ico_frog/raw/main/bg/10n_bg.png",
Shouldn’t it say this instead?
"_01d": "https://github.com/sharn25/weather_ico_frog/raw/main/bg/01d_bg.png",
I am using this for a scriptable widget on iPhone and am noticing the ‘clear’ weather shows the picture for the ‘rain night’.
Thanks!

**Comment by sharn25** [comment]
Thanks for pointing out. 

Fixed it.

**Comment by Luper06** [comment]
It’s perfect, thank you so much!
